version: "3.2"
services:
  php:
    build: './build/php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/:rw
  apache:
    build: './build/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public_html/:/var/www/html/:rw
  mysql:
    image: mysql:5.7.35
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    command: mysqld --default-authentication-plugin=mysql_native_password
networks:
  frontend:
  backend: