version: "3.2"
services:
  php:
    build: './build/php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/:rw
  apache:
    build: './build/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/:rw
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend: